# Generated by Django 4.2.16 on 2024-09-14 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_shortenedurl_id_alter_shortenedurl_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
