# Generated by Django 4.2.16 on 2024-09-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenedurl_secret_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReusableShortcodes',
        ),
        migrations.DeleteModel(
            name='URLCounter',
        ),
    ]
